[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
ffi = true
auto_detect_solc = true
via_ir = true
optimizer = true
optimizer_runs = 200

# Flare Network Configuration
[profile.flare]
chain_id = 14
rpc_url = "${FLARE_RPC_URL}"

[profile.flare_testnet]
chain_id = 16
rpc_url = "${FLARE_TESTNET_RPC_URL}"

# Script configuration
[profile.script]
ffi = true
